"""add_advanced_filter_fields_to_domain_model

Revision ID: 5c8ba15c46e2
Revises: 14e28220766a
Create Date: 2025-06-03 22:59:25.460225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8ba15c46e2'
down_revision = '14e28220766a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domains', 'name', new_column_name='domain_name_full', existing_type=sa.String(length=255), comment='Full domain name, e.g., example.com', existing_nullable=False)
    # The unique constraint and index on 'name' (now 'domain_name_full') should be preserved by alter_column if possible, or recreated if necessary.
    # If 'name' had an explicit index name like 'ix_domains_name', it might need to be dropped and recreated for 'domain_name_full'.
    # Assuming default index naming ix_domains_domain_name_full is handled or we use op.f for safety.

    op.add_column('domains', sa.Column('name_part', sa.String(length=190), nullable=False, comment="The part of the domain name before the TLD, e.g., 'example'"))
    op.create_index(op.f('ix_domains_name_part'), 'domains', ['name_part'], unique=False)
    
    op.alter_column('domains', 'tld', new_column_name='tld_part', existing_type=sa.String(length=63), comment="The TLD part of the domain, e.g., 'com' (without the dot)", existing_nullable=False)
    # Recreate index for tld_part if the old one for tld was specific or dropped.
    op.create_index(op.f('ix_domains_tld_part'), 'domains', ['tld_part'], unique=False)

    op.add_column('domains', sa.Column('name_part_length', sa.Integer(), nullable=False, comment='Length of the name_part'))
    op.create_index(op.f('ix_domains_name_part_length'), 'domains', ['name_part_length'], unique=False)
    
    op.add_column('domains', sa.Column('price', sa.Float(), nullable=True, comment='Price of the domain, if applicable'))
    op.create_index(op.f('ix_domains_price'), 'domains', ['price'], unique=False)
    
    op.add_column('domains', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=True, comment='Currency of the price (e.g., USD, EUR)'))
    
    op.add_column('domains', sa.Column('registered_date', sa.DateTime(), nullable=True, comment='Date the domain was registered'))
    op.create_index(op.f('ix_domains_registered_date'), 'domains', ['registered_date'], unique=False)
    
    op.add_column('domains', sa.Column('quality_score', sa.Float(), nullable=True, comment='A generic quality score, 0-100'))
    op.create_index(op.f('ix_domains_quality_score'), 'domains', ['quality_score'], unique=False)
    
    op.add_column('domains', sa.Column('seo_score', sa.Float(), nullable=True, comment='SEO score, 0-100'))
    op.create_index(op.f('ix_domains_seo_score'), 'domains', ['seo_score'], unique=False)
    
    op.add_column('domains', sa.Column('search_volume', sa.Integer(), nullable=True, comment='Estimated monthly search volume'))
    op.create_index(op.f('ix_domains_search_volume'), 'domains', ['search_volume'], unique=False)
    
    op.add_column('domains', sa.Column('cpc', sa.Float(), nullable=True, comment='Estimated Cost Per Click'))
    op.create_index(op.f('ix_domains_cpc'), 'domains', ['cpc'], unique=False)
    
    op.add_column('domains', sa.Column('language', sa.String(length=10), nullable=True, comment="Detected language of the domain content or target audience (e.g., 'en', 'es')"))
    op.create_index(op.f('ix_domains_language'), 'domains', ['language'], unique=False)

    # Ensure tld_type is indexed
    op.create_index(op.f('ix_domains_tld_type'), 'domains', ['tld_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domains_tld_type'), table_name='domains')
    op.drop_index(op.f('ix_domains_language'), table_name='domains')
    op.drop_column('domains', 'language')
    op.drop_index(op.f('ix_domains_cpc'), table_name='domains')
    op.drop_column('domains', 'cpc')
    op.drop_index(op.f('ix_domains_search_volume'), table_name='domains')
    op.drop_column('domains', 'search_volume')
    op.drop_index(op.f('ix_domains_seo_score'), table_name='domains')
    op.drop_column('domains', 'seo_score')
    op.drop_index(op.f('ix_domains_quality_score'), table_name='domains')
    op.drop_column('domains', 'quality_score')
    op.drop_index(op.f('ix_domains_registered_date'), table_name='domains')
    op.drop_column('domains', 'registered_date')
    op.drop_column('domains', 'currency')
    op.drop_index(op.f('ix_domains_price'), table_name='domains')
    op.drop_column('domains', 'price')
    op.drop_index(op.f('ix_domains_name_part_length'), table_name='domains')
    op.drop_column('domains', 'name_part_length')
    
    op.drop_index(op.f('ix_domains_tld_part'), table_name='domains')
    op.alter_column('domains', 'tld_part', new_column_name='tld', existing_type=sa.String(length=63), comment=None, existing_comment='The TLD part of the domain, e.g., \'com\' (without the dot)', existing_nullable=False)
    
    op.drop_index(op.f('ix_domains_name_part'), table_name='domains')
    op.drop_column('domains', 'name_part')
    
    op.alter_column('domains', 'domain_name_full', new_column_name='name', existing_type=sa.String(length=255), comment=None, existing_comment='Full domain name, e.g., example.com', existing_nullable=False)
    # ### end Alembic commands ###
